server:
  port: 8888

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 数据库源类型
    driver-class-name: com.mysql.cj.jdbc.Driver     # mysql驱动包
#    url: jdbc:mysql://101.35.192.249:3307/case?serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/case?serverTimezone=GMT%2B8
    username: root
    password: root
    dbcp2:
      minmin-idle: 5        # 数据库连接最小维持数
      initial-size: 5       # 初始化连接数
      max-total: 5          # 最大连接数
      max-wait-millis: 150  # 等待连接最大超时时间

  redis:
    port: 6379
    password: 123456

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml      # mybatis配置文件路径
  type-aliases-package: com.ttk.entity                    # 实体别名类所在包
  mapper-locations: classpath:mapper/*.xml                # mapper映射文件路径

shiro-redis:
  enabled: true
  redis-manager:
    host: 101.35.192.249:6380
    password: redis

markerhub:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，单位毫秒
    expire: 600000
    header: token

authzuser:
  userName: zhangsan
  userSex: nan

# 关闭日志输出
#logging:
#  level:
#    com.ttk.*: OFF

#  DEBUG
#  ERROR
#  FATAL
#  INFO
#  OFF
#  TRACE
#  WARN
#  trace<debug<info<warn<error<fatal
#  默认级别为info,即默认打印info及其以上级别的日志